/**
 * Build metadata snapshot. Generated by `scripts/gen-build-info.mjs`
 * into the sibling `build-info.generated.ts`; both server and client
 * import the constant from the shared package's index.
 *
 * - `sha`: short git HEAD at build time. `"dev"` when git was
 *   unavailable (tarball install). Compared on the client to detect
 *   that a server has been redeployed.
 * - `time`: commit timestamp in ms (or build time when git is missing).
 * - `notes`: last ~12 non-merge commit subjects, newest first. Used as
 *   release notes in the update modal.
 */
export interface BuildInfo {
  sha: string;
  time: number;
  notes: ReadonlyArray<{ sha: string; subject: string }>;
}
